USE [master]
GO

/****** Object:  Database [Restaurant]    Script Date: 2021/06/09 15:41:00 ******/
CREATE DATABASE [Restaurant]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Restaurant', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Restaurant.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Restaurant_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Restaurant_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Restaurant].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Restaurant] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Restaurant] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Restaurant] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Restaurant] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Restaurant] SET ARITHABORT OFF 
GO

ALTER DATABASE [Restaurant] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Restaurant] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Restaurant] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Restaurant] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Restaurant] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Restaurant] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Restaurant] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Restaurant] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Restaurant] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Restaurant] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Restaurant] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Restaurant] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Restaurant] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Restaurant] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Restaurant] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Restaurant] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Restaurant] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Restaurant] SET RECOVERY FULL 
GO

ALTER DATABASE [Restaurant] SET  MULTI_USER 
GO

ALTER DATABASE [Restaurant] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Restaurant] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Restaurant] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Restaurant] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Restaurant] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Restaurant] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Restaurant] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Restaurant] SET  READ_WRITE 
GO


